shape: sequence_diagram

C: {
  label: Core
}

HA: {
  label: handle_activation()\nTask
}

A: {
  label: activate()\nthread
}

C -> HA.1: "Activation"
HA.1.1: "get workflow from cache\nor create new instance"
HA.1.2: "run instance.activate()\nin separate thread w/ timeout"
HA.1 -> A: activate
A.1.1: "create asyncio Tasks\nset self as current event loop\nrun loop"
HA.1.3: Deadlock detected!
HA.1 -> C: "Fail task"
C -> HA.2: "Eviction job"
HA.2.1: "run instance.activate()\nin separate thread w/ timeout"
HA.2 -> A: activate
HA.2.2: Still deadlocked!\nDon't send completion to core.
A.2.1: Thread will never be used again
C.1: Slot will never be available again
