shape: sequence_diagram

CA: {
  label: "Non-workflow\nSDK Client"
}

SA: {
  label: "Cloud Cell\n\nnamespace A"
}

SB: {
  label: "Cloud Cell\n\nnamespace B"
}

NWB: {
  label: "Nexus Worker"
}

TWB: {
  label: "Task Worker"
}

CA -> SA: nexus_call(my_operation) {
  style.font-color: "#D35400"
}
SA -> SB: Nexus: Start

SB -> NWB: NexusTask: Start
NWB.note: (stateless)
NWB -> SB: start_task(my_task) {
  style.font-color: "#D35400"
}

SB.note: create\nCHASM instance\n(Task archetype)

with_retries: "CHASM-backed retries" {
  SB -> TWB: TaskTask
  TWB -> SB: result
}

SB -> SA: Nexus: callback
SA -> CA: nexus result {
  style.font-color: "green"
}
