explanation: |md
  **Each state comprises 2 substates**:
  - `start_future<OperationToken?>`
  - `result_future<Result>`

  Additionally, the `NexusOperationHandle` is itself a future.

  `await start_nexus_operation()` awaits on `start_future`.

  `await handle` awaits on `result_future`.

  In both cases, cancellation of the asyncio task results in sending

  a `cancel_nexus_operation` command.

  All other transitions throw `InvalidStateError.
| {near: top-left}

# message ResolveNexusOperationStart {
#   // Sequence number as provided by lang in the corresponding ScheduleNexusOperation command
#   uint32 seq = 1;
#   oneof status {
#       // The operation started asynchronously. Contains an ID that can be used to perform
#       // operations on the started operation by, ex, clients. A `ResolveNexusOperation` job will
#       // follow at some point.
#       string operation_id = 2;
#       // If true the operation "started" but only because it's also already resolved. A
#       // `ResolveNexusOperation` job will be in the same activation.
#       bool started_sync = 3;
#       // The operation was cancelled before it was ever sent to server (same WFT).
#       // Note that core will still send a `ResolveNexusOperation` job in the same activation, so
#       // there does not need to be an exceptional case for this in lang.
#       temporal.api.failure.v1.Failure cancelled_before_start = 4;
#   }
# }

# message ResolveNexusOperation {
#   // Sequence number as provided by lang in the corresponding ScheduleNexusOperation command
#   uint32 seq = 1;
#   nexus.NexusOperationResult result = 2;
# }
# message NexusOperationResult {
#   oneof status {
#       temporal.api.common.v1.Payload completed = 1;
#       temporal.api.failure.v1.Failure failed = 2;
#       temporal.api.failure.v1.Failure cancelled = 3;
#       temporal.api.failure.v1.Failure timed_out = 4;
#   }
# }

∅: {
  label: ∅\n∅\n\nawait start_nexus_operation()
}

StartedAsync: {
  label: Done<Token>\n∅\n\nawait handle
  style.font-color: orange
}

StartedSync: {
  label: Done<null>\n∅\n\nawait handle
  style.font-color: orange
}

ResultAvailableFromSync: {
  label: Done<null>\nDone<Result>
  style.font-color: green
}

ResultAvailableFromAsync: {
  label: Done<Token>\nDone<Result>
  style.font-color: green
}

Failed: {
  label: Done<Token or null>\nError
  style.font-color: red
}

FailedFromInit: {
  label: Error\nDone<null>
  style.font-color: red
}

# resolve_start job from Core

∅ -> StartedAsync: StartedAsync

∅ -> StartedSync: StartedSync

∅ -> FailedFromInit: CancelledBeforeStart

StartedSync -> Failed: ResultFailed

StartedSync -> Failed: ResultCancelled

StartedSync -> Failed: ResultTimedOut

StartedSync -> ResultAvailableFromSync: ResultCompleted

StartedAsync -> ResultAvailableFromAsync: ResultCompleted

StartedAsync -> Failed: ResultFailed

StartedAsync -> Failed: ResultCancelled

StartedAsync -> Failed: ResultTimedOut
