shape: sequence_diagram

explanation: |md
  # Top-level Task: within-namespace
  - New CHASM-backed product feature
| {
  near: top-center
  style.font-size: 14
}

C: {
  label: "SDK Client\n\n(workflow or\nnon-workflow)"
}

S: {
  label: "Cloud Cell"
}

TW: {
  label: "Task\nWorker"
}

TW.0: "register Task"

C -> S: start_task(my_task) {
  style.font-color: "#D35400"
}

S.1: create ASM instance\n\narchetype:\nRetryableCheckpointingTask

with_retries: "CHASM-backed retries" {
  S -> TW: TaskTask
  TW.1: "K/V checkpointing"
  TW -> S: result
}

S -> C: result {
  style.font-color: "green"
}
