shape: sequence_diagram

C: {
  label: Client
}
S: {
  label: Temporal\nServer
}
W: {
  label: Workflow
}
S.style: {
  fill: "#B664FF"
  font-color: "#EEEEEE"
}

W -> S.1: worker poll
C.1 -> S: execute\nUpdate {
  style.bold: true
}
S.1 -> W.1: Update
W.1."Update handler"
W.1 -> S.2: accept Update\nschedule Activity
S.2."UpdateAccepted\nwritten to history\n\ndispatch Activity task..."
W -> S.3: worker poll
S.3."...receive Activity result"
S.3 -> W.2: Activity result
W.2."Update handler"
W.2 -> S.3: Update\nresult {
  style.bold: true
  style.font-color: green
}
S.3."UpdateCompleted\nwritten to history"
S.3 -> C.1: Update\nresult {
  style.bold: true
  style.font-color: green
}
