shape: sequence_diagram

C: {
  label: Client
}
S: {
  label: Temporal\nServer
}
W: {
  label: Workflow
}
S.style: {
  fill: "#B664FF"
  font-color: "#EEEEEE"
}

C.1 -> S: startUpdate
W -> S.1: worker poll
S.1 -> W.1: Update that\nexecutes an Activity
W.1 -> S.2: Update\naccepted
S.2."UpdateAccepted\nwritten\nto history"
S.2 -> C.1: Update\naccepted
C.1."UpdateHandle available"
W.1."Update handler\n\nschedule Activity\n...Activity Worker...\nreceive Activity result"
C.2."Use UpdateHandle\nto fetch result"
C.2 -> S.3: fetch result
W.1 -> S.3: Update\nresult
S.3."UpdateCompleted\nwritten\nto history"
S.3 -> C.2: Update\nresult
