explanation: |md
  **Each state comprises 3 substates, arranged vertically**:
  - `UpdateRegistry` entry
  - mutable state `UpdateInfo` entry
  - history events

  **History event codes**:

  - UR = UpdateRequested
  - UA = UpdateAccepted
  - UC = UpdateCompleted

  **\+ indicates that the request payload is present**.

| {near: top-left}

∅ -> Requested+: New()\nattach request payload

# ∅ -> Admitted: New()
# Admitted -> Requested+: attach request payload
# Admitted -> ∅: lose registry
# Admitted: {
#     label: Admitted\n∅\n∅
#   }

Requested+ -> Accepted+: worker sends\naccept msg
Requested+ -> Rejected+: worker sends\nreject msg
# More accurately, with Sent state
# Requested+ -> Sent+: Send()
# Sent+ -> Accepted+: worker sends\naccept msg
# Sent+ -> Rejected+: worker sends\nreject msg
# Sent+ -> ∅: lose registry
# Sent+: {
#   label: Sent+\n∅\n∅
# }

Accepted+ -> Completed+: worker sends\ncomplete msg

Requested+ -> ∅: lose registry
# Accepted+ -> Accepted+: lose registry

∅ -> fail-wft: worker sends\naccept/reject msg

∅: {
  label: ∅\n∅\n∅\n
}
Requested+: {
  label: Requested+\n∅\n∅
}
Accepted+: {
  label: Accepted+\nAccepted\nUA+
}
Completed+: {
  label: ∅\nCompleted\nUA+,UC
}
Rejected+: {
  label: ∅\n∅\n∅
}
fail-wft: {
  label: ERROR\n(fail WFT)
  style.font-color: red
}

# With reapplied updates
Completed+ -> ReappliedR: reapply
Accepted+ -> ReappliedR: reapply
Rejected+ -> bug-reapply-rejected: reapply
ReappliedR -> ReappliedRA: worker sends\naccept msg
ReappliedRA -> ReappliedRAC: worker sends\ncomplete msg
ReappliedR -> ReappliedRAJ: worker sends\nreject msg

# Multiple reapplies
ReappliedR -> ReappliedR: reapply
ReappliedRA -> ReappliedR: reapply
ReappliedRAC -> ReappliedR: reapply
ReappliedRAJ -> ReappliedR: reapply\n(rejected\nreapplied update\nwill be reapplied!)

# Reapply states
ReappliedR: {
  label: Requested\nRequested\nUR+
}
ReappliedRA: {
  label: Accepted\nAccepted\nUR+,UA
}
ReappliedRAC: {
  label: ∅\nCompleted\nUR+,UA,UC
}
ReappliedRAJ: {
  label: ∅\nCompleted\nUR+
  style.font-color: orange
}
bug-reapply-rejected: {
  label: TEMPORAL FLAW\n(rejected update\ncannot be reapplied)
  style.font-color: red
}
