shape: sequence_diagram

C: {
  label: Client
}
S: {
  label: Temporal\nServer
}
W: {
  label: Workflow\nWorker
}
S.style: {
  fill: "#B664FF"
  font-color: "#EEEEEE"
}

C.1 -> S.1: Signal that\ntriggers an Activity
S.1 -> C.1: Ack
C."When is the Activity done?\nHow do I get the result?"
W -> S.2: poll
S.2 -> W.1: Signal that\ntriggers an Activity
W.1."Signal handler\n\nschedule Activity\n...Activity Worker...\nreceive Activity result"
W.1."How to notify Client\nthat Activity is done\n and deliver result?"
