explanation: |md
  Each state comprises 3 substates, arranged vertically. These are:
  - `UpdateRegistry` entry
  - mutable state `UpdateInfo` entry
  - history events

  \+ indicates that the request payload is present.
| {near: top-left}

∅ -> Admitted: New()
Admitted -> Requested+: attach request payload
Requested+ -> Sent+: Send()
Sent+ -> Accepted+: worker sends\naccept msg
Accepted+ -> Completed+: worker sends\ncomplete msg
Sent+ -> Rejected+: worker sends\nreject msg

Admitted -> ∅: lose registry
Requested+ -> ∅: lose registry
Sent+ -> ∅: lose registry
# Accepted+ -> Accepted+: lose registry

∅ -> fail-wft: worker sends\naccept/reject msg

∅: {
  label: ∅\n∅\n∅\n
}
Sent+: {
  label: Sent+\n∅\n∅
}
Admitted: {
  label: Admitted\n∅\n∅
}
Requested+: {
  label: Requested+\n∅\n∅
}
Accepted+: {
  label: Accepted+\nAccepted\nUA+
}
Completed+: {
  label: Completed+\n∅\nUA+,UC
}
Rejected+: {
  label: Completed+\n∅\n∅
}
fail-wft: {
  label: ERROR\n(fail WFT)
  style.font-color: red
}
