# https://github.com/temporalio/temporal/issues/6085

UpdateWorkflowExecution(wfID, upID) -> wf exists?

wf exists? -> wf running?: yes
wf exists? -> Error: no

wf running? -> update exists?\*: no
wf running? -> update exists?: yes

update exists?\* -> at requested stage already?: yes
update exists?\* -> Error: no

at requested stage already? -> return update info: yes
at requested stage already? -> Error: no

update exists? -> wait for requested stage\n\nreturn update info: yes
update exists? -> create update: no
create update -> wait for requested stage\n\nreturn update info
