shape: sequence_diagram

C: {
  label: Client
}
S: {
  label: Temporal\nServer
}
W: {
  label: Workflow\nWorker
}
S.style: {
  fill: "#B664FF"
  font-color: "#EEEEEE"
}

C.1 -> S.1: StartCluster Update
W -> S.2: poll
S.2 -> W.1: StartCluster Update
W.1 -> S.1: Update Accepted
S.1 -> C.1: Update Accepted
C.2 -> S.3: Get\nUpdate result
W.1."update handler\n\nschedule activity\n...Activity Worker...\nreceive activity result"
W.1 -> S.3: Update Completed
S.3 -> C.2: Update Completed
C."Cluster is ready to use!"
