shape: sequence_diagram

C: {
  label: Client
}
S: {
  label: Temporal\nServer
}
W: {
  label: Workflow
}
S.style: {
  fill: "#B664FF"
  font-color: "#EEEEEE"
}

W -> S.1: worker poll
C.1 -> S.1: Signal that\ntriggers an Activity
S.1."Signal\nwritten to history"
S.1 -> C.1: Ack
S.1 -> W.1: Signal
W.1."Signal handler"
W.1 -> S.2: schedule Activity
S.2."dispatch Activity task"

W -> S.3: worker poll
C.2 -> S.3: Query
S.3 -> W.2: Query
W.2 -> S.3: empty\nQuery result {
  style.font-color: red
  style.bold: true
}
S.3 -> C.2: empty\nQuery result {
  style.font-color: red
  style.bold: true
}

W -> S.4: worker poll
S."receive Activity result"

S.4 -> W.3: Activity result
W.3."Signal handler"

W.4 -> S.5: worker poll
C.3 -> S.5: Query
S.5 -> W.4: Query
W.4 -> S.5: successful\nQuery result {
  style.font-color: green
  style.bold: true
}
S.5 -> C.3: successful\nQuery result {
  style.font-color: green
  style.bold: true
}
