admitted -> requested
requested -> sent
sent -> accepted
accepted -> completed
sent -> completed

accepted -> reappliedRequested
reappliedRequested -> reappliedRequested
reappliedRequested -> reappliedSent
reappliedSent -> reappliedAccepted
reappliedAccepted -> completed
reappliedSent -> completed
