running: {
  label: running workflow\nexists
}
not-running: {
  label: no running workflow\nexists
}
running-on-conflict-fail: {
  label: conflict policy\nFAIL ❌
}
running-on-conflict-allow: {
  label: conflict policy\nALLOW ✅
}
running-on-conflict-terminate: {
  label: conflict policy\nTERMINATE
}

not-running-previous-exists: {
  label: previous workflow\nexists
}
not-running-no-previous-exists: {
  label: no previous workflow\nexists ✅
}

not-running-reuse-policy-allow: {
  label: reuse policy\nALLOW ✅
}
not-running-reuse-policy-allow-if-failed: {
  label: reuse policy\nALLOW_IF_FAILED ✅?
}
not-running-reuse-policy-reject: {
  label: reuse policy\nREJECT ❌
}

terminated-or-failed-reuse-policy-allow: {
  label: reuse policy\nALLOW ✅
}
terminated-or-failed-reuse-policy-allow-if-failed: {
  label: reuse policy\nALLOW_IF_FAILED ✅
}
terminated-or-failed-reuse-policy-reject: {
  label: reuse policy\nREJECT\n❌ invalid options
}

closed-without-failure-reuse-policy-allow: {
  label: reuse policy\nALLOW ✅
}
closed-without-failure-reuse-policy-allow-if-failed: {
  label: reuse policy\nALLOW_IF_FAILED ❌
}
# closed-without-failure-reuse-policy-reject: {
#   label: reuse policy\nREJECT
# }

start workflow -> not-running
start workflow -> running

running -> running-on-conflict-terminate
running -> running-on-conflict-fail
running -> running-on-conflict-allow

running-on-conflict-terminate -> terminated-or-failed
running-on-conflict-terminate -> closed-without-failure

terminated-or-failed -> terminated-or-failed-reuse-policy-allow
terminated-or-failed -> terminated-or-failed-reuse-policy-allow-if-failed
terminated-or-failed -> terminated-or-failed-reuse-policy-reject

closed-without-failure -> terminated-or-failed-reuse-policy-reject
closed-without-failure -> closed-without-failure-reuse-policy-allow
closed-without-failure -> closed-without-failure-reuse-policy-allow-if-failed

not-running -> not-running-previous-exists
not-running -> not-running-no-previous-exists

not-running-previous-exists -> not-running-reuse-policy-allow
not-running-previous-exists -> not-running-reuse-policy-allow-if-failed
not-running-previous-exists -> not-running-reuse-policy-reject
