running: {
  label: running workflow\nexists
}
not-running: {
  label: no running workflow\nexists
}
running-on-conflict-fail: {
  label: conflict policy\nFAIL ❌
}
running-on-conflict-allow: {
  label: conflict policy\nALLOW ✅
}
running-on-conflict-terminate: {
  label: conflict policy\nTERMINATE
}

not-running-previous-exists: {
  label: previous workflow\nexists
}
not-running-no-previous-exists: {
  label: no previous workflow\nexists ✅
}

not-running-reuse-policy-allow: {
  label: reuse policy\nALLOW ✅
}
not-running-reuse-policy-allow-if-failed: {
  label: reuse policy\nALLOW_IF_FAILED ✅?
}
not-running-reuse-policy-reject: {
  label: reuse policy\nREJECT ❌
}

running-conflict-policy-terminate-reuse-policy-allow: {
  label: reuse policy\nALLOW ✅
}
running-conflict-policy-terminate-reuse-policy-allow-if-failed: {
  label: reuse policy\nALLOW_IF_FAILED\n✅ if terminated or failed\n ❌ if closed without failure
}
running-conflict-policy-terminate-reuse-policy-reject: {
  label: reuse policy\nREJECT\n❌ invalid options
}

start workflow -> not-running
start workflow -> running

running -> running-on-conflict-terminate
running -> running-on-conflict-fail
running -> running-on-conflict-allow

running-on-conflict-terminate -> running-conflict-policy-terminate-reuse-policy-allow
running-on-conflict-terminate -> running-conflict-policy-terminate-reuse-policy-allow-if-failed
running-on-conflict-terminate -> running-conflict-policy-terminate-reuse-policy-reject

not-running -> not-running-previous-exists
not-running -> not-running-no-previous-exists

not-running-previous-exists -> not-running-reuse-policy-allow
not-running-previous-exists -> not-running-reuse-policy-allow-if-failed
not-running-previous-exists -> not-running-reuse-policy-reject
